// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mev/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryPendingBundlesRequest is the request type for querying pending bundles
type QueryPendingBundlesRequest struct {
}

func (m *QueryPendingBundlesRequest) Reset()         { *m = QueryPendingBundlesRequest{} }
func (m *QueryPendingBundlesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPendingBundlesRequest) ProtoMessage()    {}
func (*QueryPendingBundlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5054dc3f547c7ad8, []int{0}
}
func (m *QueryPendingBundlesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingBundlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingBundlesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingBundlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingBundlesRequest.Merge(m, src)
}
func (m *QueryPendingBundlesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingBundlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingBundlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingBundlesRequest proto.InternalMessageInfo

// QueryPendingBundlesResponse is the response type for querying pending bundles
type QueryPendingBundlesResponse struct {
	Bundles []Bundle `protobuf:"bytes,1,rep,name=bundles,proto3" json:"bundles"`
}

func (m *QueryPendingBundlesResponse) Reset()         { *m = QueryPendingBundlesResponse{} }
func (m *QueryPendingBundlesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPendingBundlesResponse) ProtoMessage()    {}
func (*QueryPendingBundlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5054dc3f547c7ad8, []int{1}
}
func (m *QueryPendingBundlesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingBundlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingBundlesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingBundlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingBundlesResponse.Merge(m, src)
}
func (m *QueryPendingBundlesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingBundlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingBundlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingBundlesResponse proto.InternalMessageInfo

func (m *QueryPendingBundlesResponse) GetBundles() []Bundle {
	if m != nil {
		return m.Bundles
	}
	return nil
}

// Bundle represents a MEV bundle
type Bundle struct {
	Sender    string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty" yaml:"sender"`
	Txs       []string `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty" yaml:"txs"`
	BlockNum  uint64   `protobuf:"varint,3,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty" yaml:"block_num"`
	Timestamp int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty" yaml:"timestamp"`
}

func (m *Bundle) Reset()         { *m = Bundle{} }
func (m *Bundle) String() string { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()    {}
func (*Bundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_5054dc3f547c7ad8, []int{2}
}
func (m *Bundle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Bundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Bundle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Bundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bundle.Merge(m, src)
}
func (m *Bundle) XXX_Size() int {
	return m.Size()
}
func (m *Bundle) XXX_DiscardUnknown() {
	xxx_messageInfo_Bundle.DiscardUnknown(m)
}

var xxx_messageInfo_Bundle proto.InternalMessageInfo

func (m *Bundle) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Bundle) GetTxs() []string {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *Bundle) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *Bundle) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryPendingBundlesRequest)(nil), "seiprotocol.seichain.mev.QueryPendingBundlesRequest")
	proto.RegisterType((*QueryPendingBundlesResponse)(nil), "seiprotocol.seichain.mev.QueryPendingBundlesResponse")
	proto.RegisterType((*Bundle)(nil), "seiprotocol.seichain.mev.Bundle")
}

func init() { proto.RegisterFile("mev/query.proto", fileDescriptor_5054dc3f547c7ad8) }

var fileDescriptor_5054dc3f547c7ad8 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xb1, 0x8e, 0xd3, 0x30,
	0x18, 0xc7, 0xeb, 0x4b, 0x29, 0xd4, 0x88, 0xe3, 0xb0, 0x6e, 0x88, 0xca, 0x29, 0x8d, 0x3c, 0x05,
	0x44, 0x13, 0x51, 0x60, 0x61, 0x42, 0x59, 0xd8, 0x10, 0x64, 0x64, 0xa9, 0xdc, 0xf4, 0x53, 0xce,
	0x22, 0xb6, 0x73, 0xb1, 0x73, 0x6a, 0x57, 0x9e, 0x00, 0x89, 0x27, 0x61, 0x86, 0x07, 0xb8, 0xf1,
	0x24, 0x16, 0xa6, 0x08, 0xb5, 0x3c, 0x41, 0x9f, 0x00, 0x25, 0x4e, 0x0b, 0x08, 0x3a, 0xb0, 0x7d,
	0xfa, 0x7e, 0xff, 0xff, 0xdf, 0xd6, 0xff, 0xc3, 0x77, 0x05, 0x5c, 0x46, 0x17, 0x15, 0x94, 0xab,
	0xb0, 0x28, 0x95, 0x51, 0xc4, 0xd5, 0xc0, 0xdb, 0x29, 0x55, 0x79, 0xa8, 0x81, 0xa7, 0xe7, 0x8c,
	0xcb, 0x50, 0xc0, 0xe5, 0xe8, 0x34, 0x53, 0x99, 0x6a, 0x51, 0xd4, 0x4c, 0x56, 0x3f, 0x3a, 0xcb,
	0x94, 0xca, 0x72, 0x88, 0x58, 0xc1, 0x23, 0x26, 0xa5, 0x32, 0xcc, 0x70, 0x25, 0x75, 0x47, 0x4f,
	0x9a, 0xf8, 0x82, 0x95, 0x4c, 0x74, 0x1b, 0x7a, 0x86, 0x47, 0x6f, 0x9a, 0xe7, 0x5e, 0x83, 0x5c,
	0x70, 0x99, 0xc5, 0x95, 0x5c, 0xe4, 0xa0, 0x13, 0xb8, 0xa8, 0x40, 0x1b, 0x3a, 0xc3, 0xf7, 0xff,
	0x49, 0x75, 0xa1, 0xa4, 0x06, 0xf2, 0x02, 0xdf, 0x9c, 0xdb, 0x95, 0x8b, 0x7c, 0x27, 0xb8, 0x3d,
	0xf5, 0xc3, 0x43, 0xdf, 0x0d, 0xad, 0x37, 0xee, 0x5f, 0xd5, 0xe3, 0x5e, 0xb2, 0xb3, 0xd1, 0x2f,
	0x08, 0x0f, 0x2c, 0x21, 0x0f, 0xf0, 0x40, 0x83, 0x5c, 0x40, 0xe9, 0x22, 0x1f, 0x05, 0xc3, 0xf8,
	0xde, 0xb6, 0x1e, 0xdf, 0x59, 0x31, 0x91, 0x3f, 0xa7, 0x76, 0x4f, 0x93, 0x4e, 0x40, 0x7c, 0xec,
	0x98, 0xa5, 0x76, 0x8f, 0x7c, 0x27, 0x18, 0xc6, 0xc7, 0xdb, 0x7a, 0x8c, 0xad, 0xce, 0x2c, 0x35,
	0x4d, 0x1a, 0x44, 0x1e, 0xe3, 0xe1, 0x3c, 0x57, 0xe9, 0xbb, 0x99, 0xac, 0x84, 0xeb, 0xf8, 0x28,
	0xe8, 0xc7, 0xa7, 0xdb, 0x7a, 0x7c, 0x62, 0x75, 0x7b, 0x44, 0x93, 0x5b, 0xed, 0xfc, 0xaa, 0x12,
	0x64, 0x8a, 0x87, 0x86, 0x0b, 0xd0, 0x86, 0x89, 0xc2, 0xed, 0xfb, 0x28, 0x70, 0x7e, 0xb7, 0xec,
	0x11, 0x4d, 0x7e, 0xc9, 0xa6, 0x9f, 0x11, 0xbe, 0xd1, 0x16, 0x44, 0x3e, 0x21, 0x7c, 0xfc, 0x67,
	0x4b, 0xe4, 0xe9, 0xe1, 0x32, 0x0e, 0x57, 0x3e, 0x7a, 0xf6, 0x9f, 0x2e, 0x7b, 0x0a, 0x3a, 0x7d,
	0xff, 0xf5, 0xc7, 0xc7, 0xa3, 0x47, 0xe4, 0x61, 0xa4, 0x81, 0x4f, 0x76, 0xfe, 0x68, 0xe7, 0x8f,
	0xda, 0xc3, 0x5b, 0xeb, 0xac, 0x2b, 0x3f, 0x7e, 0x79, 0xb5, 0xf6, 0xd0, 0xf5, 0xda, 0x43, 0xdf,
	0xd7, 0x1e, 0xfa, 0xb0, 0xf1, 0x7a, 0xd7, 0x1b, 0xaf, 0xf7, 0x6d, 0xe3, 0xf5, 0xde, 0x4e, 0x32,
	0x6e, 0xce, 0xab, 0x79, 0x98, 0x2a, 0xf1, 0x57, 0xde, 0xc4, 0x06, 0x2e, 0xdb, 0x48, 0xb3, 0x2a,
	0x40, 0xcf, 0x07, 0x2d, 0x7f, 0xf2, 0x33, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x67, 0x5b, 0xe4, 0xbe,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// PendingBundles queries all pending MEV bundles
	PendingBundles(ctx context.Context, in *QueryPendingBundlesRequest, opts ...grpc.CallOption) (*QueryPendingBundlesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PendingBundles(ctx context.Context, in *QueryPendingBundlesRequest, opts ...grpc.CallOption) (*QueryPendingBundlesResponse, error) {
	out := new(QueryPendingBundlesResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.mev.Query/PendingBundles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// PendingBundles queries all pending MEV bundles
	PendingBundles(context.Context, *QueryPendingBundlesRequest) (*QueryPendingBundlesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PendingBundles(ctx context.Context, req *QueryPendingBundlesRequest) (*QueryPendingBundlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingBundles not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PendingBundles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingBundlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingBundles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.mev.Query/PendingBundles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingBundles(ctx, req.(*QueryPendingBundlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seiprotocol.seichain.mev.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PendingBundles",
			Handler:    _Query_PendingBundles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mev/query.proto",
}

func (m *QueryPendingBundlesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingBundlesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingBundlesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPendingBundlesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingBundlesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingBundlesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Bundles) > 0 {
		for iNdEx := len(m.Bundles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Bundles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Bundle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Bundle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Bundle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if m.BlockNum != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlockNum))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Txs) > 0 {
		for iNdEx := len(m.Txs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Txs[iNdEx])
			copy(dAtA[i:], m.Txs[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Txs[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPendingBundlesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPendingBundlesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Bundles) > 0 {
		for _, e := range m.Bundles {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *Bundle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Txs) > 0 {
		for _, s := range m.Txs {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.BlockNum != 0 {
		n += 1 + sovQuery(uint64(m.BlockNum))
	}
	if m.Timestamp != 0 {
		n += 1 + sovQuery(uint64(m.Timestamp))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPendingBundlesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingBundlesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingBundlesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingBundlesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingBundlesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingBundlesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bundles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bundles = append(m.Bundles, Bundle{})
			if err := m.Bundles[len(m.Bundles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Bundle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bundle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bundle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txs = append(m.Txs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockNum", wireType)
			}
			m.BlockNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
