// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mev/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitBundle represents a message to submit a bundle of transactions
type MsgSubmitBundle struct {
	Sender    string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty" yaml:"sender"`
	Txs       [][]byte `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty" yaml:"txs"`
	BlockNum  uint64   `protobuf:"varint,3,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty" yaml:"block_num"`
	Timestamp int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty" yaml:"timestamp"`
}

func (m *MsgSubmitBundle) Reset()         { *m = MsgSubmitBundle{} }
func (m *MsgSubmitBundle) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBundle) ProtoMessage()    {}
func (*MsgSubmitBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_956295f2d06f0125, []int{0}
}
func (m *MsgSubmitBundle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBundle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBundle.Merge(m, src)
}
func (m *MsgSubmitBundle) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBundle.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBundle proto.InternalMessageInfo

func (m *MsgSubmitBundle) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgSubmitBundle) GetTxs() [][]byte {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *MsgSubmitBundle) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *MsgSubmitBundle) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// MsgSubmitBundleResponse defines the response structure
type MsgSubmitBundleResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty" yaml:"success"`
}

func (m *MsgSubmitBundleResponse) Reset()         { *m = MsgSubmitBundleResponse{} }
func (m *MsgSubmitBundleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBundleResponse) ProtoMessage()    {}
func (*MsgSubmitBundleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956295f2d06f0125, []int{1}
}
func (m *MsgSubmitBundleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBundleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBundleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBundleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBundleResponse.Merge(m, src)
}
func (m *MsgSubmitBundleResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBundleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBundleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBundleResponse proto.InternalMessageInfo

func (m *MsgSubmitBundleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*MsgSubmitBundle)(nil), "seiprotocol.seichain.mev.MsgSubmitBundle")
	proto.RegisterType((*MsgSubmitBundleResponse)(nil), "seiprotocol.seichain.mev.MsgSubmitBundleResponse")
}

func init() { proto.RegisterFile("mev/tx.proto", fileDescriptor_956295f2d06f0125) }

var fileDescriptor_956295f2d06f0125 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xb1, 0x8e, 0xd3, 0x30,
	0x18, 0xc7, 0x6b, 0x72, 0x3a, 0xae, 0x56, 0x39, 0xc0, 0x3a, 0x89, 0xa8, 0x43, 0x12, 0x79, 0x0a,
	0x12, 0x17, 0x2b, 0x65, 0x63, 0xcc, 0xd2, 0xa9, 0x0c, 0x61, 0x63, 0x41, 0x89, 0x6b, 0xa5, 0x16,
	0x71, 0x1c, 0xf5, 0x73, 0xaa, 0xf4, 0x2d, 0x78, 0x29, 0x24, 0xc6, 0x8e, 0x4c, 0x11, 0x6a, 0xdf,
	0x20, 0x4f, 0x80, 0xea, 0xb4, 0x05, 0x2a, 0x21, 0xdd, 0xf6, 0xd9, 0xbf, 0x9f, 0x3f, 0xfb, 0xff,
	0xc9, 0x78, 0xa2, 0xc4, 0x86, 0x99, 0x36, 0xaa, 0xd7, 0xda, 0x68, 0xe2, 0x82, 0x90, 0xb6, 0xe2,
	0xba, 0x8c, 0x40, 0x48, 0xbe, 0xca, 0x64, 0x15, 0x29, 0xb1, 0x99, 0x3e, 0x14, 0xba, 0xd0, 0x16,
	0xb1, 0x63, 0x35, 0xf8, 0x53, 0x8f, 0x6b, 0x50, 0x1a, 0x58, 0x9e, 0x81, 0x60, 0x9b, 0x38, 0x17,
	0x26, 0x8b, 0x19, 0xd7, 0xb2, 0x1a, 0x38, 0xfd, 0x8e, 0xf0, 0xcb, 0x05, 0x14, 0x9f, 0x9a, 0x5c,
	0x49, 0x93, 0x34, 0xd5, 0xb2, 0x14, 0xe4, 0x2d, 0xbe, 0x05, 0x51, 0x2d, 0xc5, 0xda, 0x45, 0x01,
	0x0a, 0xc7, 0xc9, 0xeb, 0xbe, 0xf3, 0x5f, 0x6c, 0x33, 0x55, 0x7e, 0xa0, 0xc3, 0x3e, 0x4d, 0x4f,
	0x02, 0x09, 0xb0, 0x63, 0x5a, 0x70, 0x9f, 0x05, 0x4e, 0x38, 0x49, 0xee, 0xfb, 0xce, 0xc7, 0x83,
	0x67, 0x5a, 0xa0, 0xe9, 0x11, 0x91, 0x18, 0x8f, 0xf3, 0x52, 0xf3, 0xaf, 0x5f, 0xaa, 0x46, 0xb9,
	0x4e, 0x80, 0xc2, 0x9b, 0xe4, 0xa1, 0xef, 0xfc, 0x57, 0x83, 0x77, 0x41, 0x34, 0xbd, 0xb3, 0xf5,
	0xc7, 0x46, 0x91, 0x19, 0x1e, 0x1b, 0xa9, 0x04, 0x98, 0x4c, 0xd5, 0xee, 0x4d, 0x80, 0x42, 0xe7,
	0xef, 0x23, 0x17, 0x44, 0xd3, 0x3f, 0x1a, 0x9d, 0xe3, 0x37, 0x57, 0x31, 0x52, 0x01, 0xb5, 0xae,
	0x40, 0x90, 0x77, 0xf8, 0x39, 0x34, 0x9c, 0x0b, 0x00, 0x9b, 0xe7, 0x2e, 0x21, 0x7d, 0xe7, 0xdf,
	0x9f, 0xf2, 0x0c, 0x80, 0xa6, 0x67, 0x65, 0x06, 0xd8, 0x59, 0x40, 0x41, 0x4a, 0x3c, 0xf9, 0x77,
	0x26, 0xd1, 0xff, 0x06, 0x1f, 0x5d, 0xdd, 0x3b, 0x8d, 0x9f, 0xac, 0x9e, 0x9f, 0x98, 0xcc, 0x7f,
	0xec, 0x3d, 0xb4, 0xdb, 0x7b, 0xe8, 0xd7, 0xde, 0x43, 0xdf, 0x0e, 0xde, 0x68, 0x77, 0xf0, 0x46,
	0x3f, 0x0f, 0xde, 0xe8, 0xf3, 0x63, 0x21, 0xcd, 0xaa, 0xc9, 0x23, 0xae, 0x15, 0x03, 0x21, 0x1f,
	0xcf, 0x7d, 0xed, 0xc2, 0x36, 0x66, 0x2d, 0xb3, 0x3f, 0x64, 0x5b, 0x0b, 0xc8, 0x6f, 0x2d, 0x7f,
	0xff, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x75, 0xcf, 0x86, 0x35, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitBundle(ctx context.Context, in *MsgSubmitBundle, opts ...grpc.CallOption) (*MsgSubmitBundleResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitBundle(ctx context.Context, in *MsgSubmitBundle, opts ...grpc.CallOption) (*MsgSubmitBundleResponse, error) {
	out := new(MsgSubmitBundleResponse)
	err := c.cc.Invoke(ctx, "/seiprotocol.seichain.mev.Msg/SubmitBundle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitBundle(context.Context, *MsgSubmitBundle) (*MsgSubmitBundleResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitBundle(ctx context.Context, req *MsgSubmitBundle) (*MsgSubmitBundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBundle not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitBundle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seiprotocol.seichain.mev.Msg/SubmitBundle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitBundle(ctx, req.(*MsgSubmitBundle))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seiprotocol.seichain.mev.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBundle",
			Handler:    _Msg_SubmitBundle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mev/tx.proto",
}

func (m *MsgSubmitBundle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBundle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBundle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if m.BlockNum != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockNum))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Txs) > 0 {
		for iNdEx := len(m.Txs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Txs[iNdEx])
			copy(dAtA[i:], m.Txs[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Txs[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitBundleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBundleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBundleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitBundle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Txs) > 0 {
		for _, b := range m.Txs {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.BlockNum != 0 {
		n += 1 + sovTx(uint64(m.BlockNum))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTx(uint64(m.Timestamp))
	}
	return n
}

func (m *MsgSubmitBundleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitBundle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBundle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBundle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txs = append(m.Txs, make([]byte, postIndex-iNdEx))
			copy(m.Txs[len(m.Txs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockNum", wireType)
			}
			m.BlockNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitBundleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBundleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBundleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
